### PR TITLE
setUpClass instead of setUp, fixes #61

### LINKED ISSUE #61: Use setUpClass where possible instead of setUp
Using `setUpClass` and `tearDownClass` can make the tests much more efficient.

### PR DESCRIPTION
**Pull request by peterbe**
@twobraids r?

Now, instead of making about ~90 connections it only makes 2 (because there are 2 test cases that use that base class).

### CODE REVIEW

**Comment by peterbe** [comment]
ping @twobraids

**Comment by peterbe** [comment]
@twobraids I've rebased this now for a final travis check. r?

**Comment by peterbe** [comment]
@twobraids ping.

I'm intrigued to take this for a spin in socorro because I think it'll speed things up because it'll keep a connection across tests.

**Comment by adngdb** [comment]
lgtm

**Pull request merged**
